# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage ""
  version "1.10.1"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_darwin_arm64.tar.gz"
      sha256 "e03e49a2276912cf3aeadfe61928c3b845d0ca983cd653ba2eb7dbdaf575629b"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_darwin_amd64.tar.gz"
      sha256 "52882a41c37648e39dd54fa20e8881e5dcba58f38b71028b764d76816831fc2d"

      def install
        bin.install "console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_linux_arm64.tar.gz"
      sha256 "a91703e743d09a9a2e62f84cf2acf5cbc1d5dbc75acde97ac120206c88a5e83b"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_linux_amd64.tar.gz"
      sha256 "cfb16aa58a2a52c7002365b0c27321311604bb9e250e18f7346ab641d506fbd8"

      def install
        bin.install "console"
      end
    end
  end
end
