# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc ""
  homepage ""
  version "1.10.1"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_darwin_arm64.tar.gz"
      sha256 "f602dc94c0825bb58dbbcfada06e237266afc5b181b1c8eed9b9948678f482f1"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_darwin_amd64.tar.gz"
      sha256 "010dcb6bab58c98f2d26d964762e2dcadb0856842cf8dd44c7bc071dbb02baf3"

      def install
        bin.install "console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_linux_arm64.tar.gz"
      sha256 "00c182aa1a3d6a4240e0487a2520a9e7f42cc1a3e357f29b85bf818878776988"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/cli/releases/download/v1.10.1/cli_1.10.1_linux_amd64.tar.gz"
      sha256 "7fec10a12089581c005748d017888d2ad3e41b35cfcfa0672fc3a69560f88cd9"

      def install
        bin.install "console"
      end
    end
  end
end
