# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Console < Formula
  desc ""
  homepage ""
  version "2.7.3"

  depends_on "helm"
  depends_on "kubernetes-cli"
  depends_on "vmware/pinniped/pinniped-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/console/releases/download/v2.7.3/console_2.7.3_darwin_amd64.tar.gz"
      sha256 "fb1e0facdf344895e160bf80f69fdf52113829c95270f254e9c8d6cab2740344"

      define_method(:install) do
        bin.install "console"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/platformplane/console/releases/download/v2.7.3/console_2.7.3_darwin_arm64.tar.gz"
      sha256 "95e105f3ccfbdcf509c37cefcc88617062bcf7356eeed8fcea9bc6404113407b"

      define_method(:install) do
        bin.install "console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/console/releases/download/v2.7.3/console_2.7.3_linux_amd64.tar.gz"
      sha256 "f6fa04f1a47c24ee55e9f862c42c2e7b60c77f451a72e5dc8ee7c9c9e483e52f"
      define_method(:install) do
        bin.install "console"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/console/releases/download/v2.7.3/console_2.7.3_linux_arm64.tar.gz"
      sha256 "1fe074240dab579e40aefcd59f9d9b85e681da5b5b18d6f64bc0fa1c68a4d4e5"
      define_method(:install) do
        bin.install "console"
      end
    end
  end
end
