# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Console < Formula
  desc ""
  homepage ""
  version "1.15.3"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformplane/console/releases/download/v1.15.3/console_1.15.3_darwin_arm64.tar.gz"
      sha256 "a88abab673e37663217be64d9bdb011ff9e2ed3a9d493403cb1dda63718eedf6"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/console/releases/download/v1.15.3/console_1.15.3_darwin_amd64.tar.gz"
      sha256 "3ced98bab0bf6893d886274e390dd9d0196c3c39227843fbc56c5fbb0b76640b"

      def install
        bin.install "console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/console/releases/download/v1.15.3/console_1.15.3_linux_arm64.tar.gz"
      sha256 "14af597f160d1a15e46d418257b03f41a47a54d3327118537a4ea44900a9ada7"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/console/releases/download/v1.15.3/console_1.15.3_linux_amd64.tar.gz"
      sha256 "aae28d4425405a93315d95fa025acca84f2d222e158262a64bcdcbc94a891444"

      def install
        bin.install "console"
      end
    end
  end
end
