# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Platformplane < Formula
  desc ""
  homepage ""
  version "1.10.1"

  depends_on "helm"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/platformplane/platformplane/releases/download/v1.10.1/platformplane_1.10.1_darwin_arm64.tar.gz"
      sha256 "f603dd9cd66bc5f4936df1acc1ae006a19d00692e76bc894b5f33455b897aa53"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/platformplane/releases/download/v1.10.1/platformplane_1.10.1_darwin_amd64.tar.gz"
      sha256 "66256dac2d0a60f44a38599b8ff218e369a9acdfd616ad0b29672b5c15952878"

      def install
        bin.install "console"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformplane/platformplane/releases/download/v1.10.1/platformplane_1.10.1_linux_arm64.tar.gz"
      sha256 "9e376aaa3a4236ccaa8490841ce8114db8ebd82f037a15228be3ed19e706bf75"

      def install
        bin.install "console"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformplane/platformplane/releases/download/v1.10.1/platformplane_1.10.1_linux_amd64.tar.gz"
      sha256 "f9f9ff9881e7c5da8701b9442d55ab985de55d27f20064b29f1a213e5a323daf"

      def install
        bin.install "console"
      end
    end
  end
end
